# Generated by Django 2.2.5 on 2020-05-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tureta', models.IntegerField()),
                ('engine', models.IntegerField()),
                ('tracks', models.IntegerField()),
                ('front', models.IntegerField()),
            ],
        ),
    ]
