# Generated by Django 2.2.5 on 2020-05-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tancparts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panzer',
            name='health',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
