# Generated by Django 2.2.5 on 2020-05-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tancparts', '0002_panzer_health'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tureta', models.IntegerField()),
                ('engine', models.IntegerField()),
                ('tracks', models.IntegerField()),
                ('front', models.IntegerField()),
                ('health', models.IntegerField()),
            ],
        ),
    ]
